add dark mode toggle
ClimateTown/knowledge-hub pull request #295
Opened 2023-07-11 03:15 UTC by dmlb

## Describe your changes

- update tailwind dark mode config to be class-based
- check os settings when initializing and save user selection in local storage
- toggle classes for dark mode
- update tag dark mode CSS to use classes
- componentize button/button links for consistent styles dark/hover/disable
- componentize tag wrapper
- componentize checkbox

## Related issue number/link

Thanks for contributing! 🥳🚀🌳

2023-07-14 06:28 UTC, VeckoTheGecko commented
We use [Bootstrap Icons](https://icons.getbootstrap.com/icons/sun-fill/) for the icons (I'll update the README in another PR with this info).

Icons ideas:

- [Sun (light mode)](https://icons.getbootstrap.com/icons/sun-fill/)
- [Moon (dark mode)](https://icons.getbootstrap.com/icons/moon-stars-fill/)
- [Intersection (and)](https://icons.getbootstrap.com/icons/intersect/)
- [Union (or)](https://icons.getbootstrap.com/icons/union/)

2023-07-21 23:11 UTC, VeckoTheGecko commented
Updated icons:
![image](https://github.com/ClimateTown/knowledge-hub/assets/36369090/dd78915c-c086-4ba9-9764-2d0310f0e3f1)
![image](https://github.com/ClimateTown/knowledge-hub/assets/36369090/4459742a-8507-4870-84ef-0eb9a979f37c)

2023-07-22 01:25 UTC, VeckoTheGecko requested changes
Thanks @dmlb for this featureset! Great usability progress and welcome features with the filter modes and dark mode toggle.

Still some work to be done with refactoring (namely reducing duplication in filter handlers), but this is a huge step in the right direction. Further refactoring can be done in other PRs.

A couple minor points to address before shipping.

2023-07-22 01:25 UTC, VeckoTheGecko commented on tailwind.config.cjs
> +  darkMode: "class",
Just wondering, what does this do?

2023-07-22 01:26 UTC, VeckoTheGecko commented
Any opinions on using [TypeScript enums](https://www.typescriptlang.org/docs/handbook/enums.html) for categorical options in the codebase rather than strings? No need to push any changes re. them (the types `<string> | <string>` are expressive as is), just curious whether you've encountered them before and whether its something to consider in the codebase in general for some items.

2023-07-24 15:18 UTC, dmlb commented on src/lib/components/FilterForm.svelte
> +{#if filterOptions}
it protects loading binding all the logic if it were loaded and incorrect props passed, but low concern in such a small codebase I'm guessing
good habits die hard 😆

2023-07-24 16:54 UTC, VeckoTheGecko commented on src/lib/components/FilterForm.svelte
> +{#if filterOptions}
Ah I see. I think you've thought it through more than I have, happy to leave the decision up to you :)

2023-07-24 16:56 UTC, VeckoTheGecko commented
I think that all good now. Let me know if we're good to merge @dmlb and we'll get this shipped

2023-07-24 18:14 UTC, dmlb commented
> I think that all good now. Let me know if we're good to merge @dmlb and we'll get this shipped

good to go :+1:

2023-07-25 02:22 UTC, VeckoTheGecko approved these changes

2023-07-25 02:23 UTC, merged