Resource Filter Settings in URL
ClimateTown/knowledge-hub pull request #361
Opened 2023-11-10 00:40 UTC by dmlb

## Describe your changes
Query Params for search, tags, mode
- onMount for initial navigation
- $ for catching changes between URL and components
- replaceQuery HistoryAPI update to URL

## Related issue number/link
https://github.com/ClimateTown/knowledge-hub/issues/360

2023-11-20 14:03 UTC, VeckoTheGecko requested changes
Thanks for this feature. Questions about emojis in URL, and code quality/transparency items before shipping.

Happy to help with dev if you want me to push changes.

2023-11-23 19:35 UTC, dmlb commented on src/lib/components/FilterForm.svelte
> +  $: filterLogic = filterLogicAndCtrl ? "and" : "or"
you'd have to run the check against "and"/"or" to get a boolean for the HMTL attribute 🤔

2023-11-23 19:37 UTC, dmlb commented on src/routes/resources/+page.svelte
> +  let query: string | null
in the URL param also?

2023-11-24 16:11 UTC, VeckoTheGecko commented on src/routes/resources/+page.svelte
> +  let query: string | null
I think leave `q` in the URL param (I think thats common practice from what I've seen?) :)

2023-11-24 16:12 UTC, VeckoTheGecko commented on src/lib/components/FilterForm.svelte
> +  $: filterLogic = filterLogicAndCtrl ? "and" : "or"
Yeah thats a fair point. No avoiding it I guess, and nitpicky at that point 😅. All good how it is

2023-12-28 09:32 UTC, VeckoTheGecko approved these changes
LGTM now! Happy to merge

2023-12-28 09:37 UTC, merged